theme: jekyll-theme-minimal
title: Seoul Culture Guide
description: 진짜 서울을 경험하세요

# 다국어 설정
languages: ["ko", "en", "cn"]
default_lang: "ko"

# 네비게이션
# header_pages:
#   - about.md
#   - tours.md
#   - contact.md
#   - en/about.md
#   - en/tours.md
#   - cn/about.md
#   - cn/tours.md
